#!/bin/sh

### BEGIN INIT INFO
# Provides:          eufySecurity
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

dir="/usr/local/addons/eufySecurity"
cmd="/usr/local/addons/eufySecurity/bin/node /usr/local/addons/eufySecurity/apiServer.js"
user="root"

name=`basename $0`
pid_file="/var/run/eufySecurity.pid"
stdout_log="/var/log/$name.log"
stderr_log="/var/log/$name.err"

get_pid() {
    cat "$pid_file"
}

is_running() {
    #[ -f "$pid_file" ] && ps -p `get_pid` > /dev/null 2>&1
	[ -f "$pid_file" ] && ps | grep -v 'grep' | grep `get_pid` > /dev/null 2>&1
}

case "$1" in
    start)
    if is_running; then
        echo "Already started"
    else
        echo "Starting $name"
        cd "$dir"
        if [ -z "$user" ]; then
            $cmd >> "$stdout_log" 2>> "$stderr_log" &
        else
            $cmd >> "$stdout_log" 2>> "$stderr_log" &
        fi
		echo $! > "$pid_file"
        if ! is_running; then
            echo "Unable to start, see $stdout_log and $stderr_log"
            exit 1
        fi
    fi
    ;;
    stop)
    if is_running; then
        echo -n "Stopping $name.."
        kill `get_pid`
        for i in 1 2 3 4 5 6 7 8 9 10
        # for i in `seq 10`
        do
            if ! is_running; then
                break
            fi

            echo -n "."
            sleep 1
        done
        echo

        if is_running; then
            echo "Not stopped; may still be shutting down or shutdown may have failed"
            exit 1
        else
            echo "Stopped"
            if [ -f "$pid_file" ]; then
                rm "$pid_file"
            fi
        fi
    else
        echo "Not running"
    fi
    ;;
    restart)
    $0 stop
    if is_running; then
        echo "Unable to stop, will not attempt to start"
        exit 1
    fi
    $0 start
    ;;
    status)
    if is_running; then
        echo "Running"
    else
        echo "Stopped"
        exit 1
    fi
    ;;
	info)
    if [ -d $dir ]; then
        VER=$(cat $dir/VERSION)
        echo "Version: $VER"
        echo "Info: <b>eufy Security AddOn</b><br>"
		echo "Info: Erm&ouml;glicht die Steuerung des eufy Security Systems.<br>"
        echo "Info: &copy; 2020-2021 Philipp Engler<br>"
        echo "Info: <a href='https://github.com/PhilippEngler/eufy-security-hm'>Projektseite</a>"
        echo "Name: eufy SECURITY"
        echo "Operations: uninstall restart"
        echo "Config-Url: /addons/eufySecurity"
        echo "Update: /addons/eufySecurity/update-check.cgi"
    fi
    ;;
	uninstall)
        $0 stop
		if is_running; then
		    echo "Unable to stop, will not attempt to uninstall"
			exit 1
		fi
        rm -rf $dir
        rm -rf /usr/local/etc/config/addons/www/eufySecurity
        rm -rf /usr/local/etc/config/addons/www/rc.d/eufySecurity
    ;;
    *)
    echo "Usage: $0 {start|stop|restart|status|info}"
    exit 1
    ;;
esac

exit 0