#!/bin/sh

ADDONNAME=eufySecurity
CONFIG_DIR=/usr/local/etc/config
ADDON_DIR=/usr/local/addons/${ADDONNAME}
RCD_DIR=${CONFIG_DIR}/rc.d
WWW_DIR=${CONFIG_DIR}/addons/www/${ADDONNAME}

# check for unsupported platforms (author: jens-maus)
if grep -qim1 busmatic /www/api/methods/ccu/downloadFirmware.tcl; then
  exit 13
fi

# mount /usr/local if not already mounted
mount | grep /usr/local 2>&1 >/dev/null
if [ $? -eq 1 ]; then
  mount /usr/local
fi

# if the service is available, stop it
# (mainly for raspberrymatic)
if [ -e ${RCD_DIR}/eufySecurity ]; then
  ${RCD_DIR}/eufySecurity stop
fi

# remove unused api files from versions lower than 1.1
if [ -e ${ADDON_DIR}/eufySecurityApi ]; then
  if [ -e ${ADDON_DIR}/eufySecurityApi/http/http.service.js ]; then
    rm -f ${ADDON_DIR}/eufySecurityApi/http/http.service.js
  fi
  if [ -e ${ADDON_DIR}/eufySecurityApi/http/http.utils.js ]; then
    rm -f ${ADDON_DIR}/eufySecurityApi/http/http.utils.js
  fi
  if [ -e ${ADDON_DIR}/eufySecurityApi/http/http-request.models.js ]; then
    rm -f ${ADDON_DIR}/eufySecurityApi/http/http-request.models.js
  fi
  if [ -e ${ADDON_DIR}/eufySecurityApi/http/http-response.models.js ]; then
    rm -f ${ADDON_DIR}/eufySecurityApi/http/http-response.models.js
  fi
  if [ -e ${ADDON_DIR}/eufySecurityApi/p2p/cloud-lookup.service.js ]; then
    rm -f ${ADDON_DIR}/eufySecurityApi/p2p/cloud-lookup.service.js
  fi
  if [ -e ${ADDON_DIR}/eufySecurityApi/p2p/command.model.js ]; then
    rm -f ${ADDON_DIR}/eufySecurityApi/p2p/command.model.js
  fi
  if [ -e ${ADDON_DIR}/eufySecurityApi/p2p/device-client.service.js ]; then
    rm -f ${ADDON_DIR}/eufySecurityApi/p2p/device-client.service.js
  fi
  if [ -e ${ADDON_DIR}/eufySecurityApi/p2p/ip.utils.js ]; then
    rm -f ${ADDON_DIR}/eufySecurityApi/p2p/ip.utils.js
  fi
  if [ -e ${ADDON_DIR}/eufySecurityApi/p2p/local-lookup.service.js ]; then
    rm -f ${ADDON_DIR}/eufySecurityApi/p2p/local-lookup.service.js
  fi
  if [ -e ${ADDON_DIR}/eufySecurityApi/p2p/message.utils.js ]; then
    rm -f ${ADDON_DIR}/eufySecurityApi/p2p/message.utils.js
  fi
  if [ -e ${ADDON_DIR}/eufySecurityApi/p2p/payload.utils.js ]; then
    rm -f ${ADDON_DIR}/eufySecurityApi/p2p/payload.utils.js
  fi
  if [ -e ${ADDON_DIR}/eufySecurityApi/push/fid.model.js ]; then
    rm -f ${ADDON_DIR}/eufySecurityApi/push/fid.model.js
  fi
  if [ -e ${ADDON_DIR}/eufySecurityApi/push/push.model.js ]; then
    rm -f ${ADDON_DIR}/eufySecurityApi/push/push.model.js
  fi
  if [ -e ${ADDON_DIR}/eufySecurityApi/push/push.utils.js ]; then
    rm -f ${ADDON_DIR}/eufySecurityApi/push/push.utils.js
  fi
  if [ -e ${ADDON_DIR}/eufySecurityApi/push/push-client.service.js ]; then
    rm -f ${ADDON_DIR}/eufySecurityApi/push/push-client.service.js
  fi
  if [ -e ${ADDON_DIR}/eufySecurityApi/push/push-client-parser.service.js ]; then
    rm -f ${ADDON_DIR}/eufySecurityApi/push/push-client-parser.service.js
  fi
  if [ -e ${ADDON_DIR}/eufySecurityApi/push/push-register.service.js ]; then
    rm -f ${ADDON_DIR}/eufySecurityApi/push/push-register.service.js
  fi
  # remove unused node_modules files from versions lower than 1.5
  if [ -e ${ADDON_DIR}/node_modules/.bin ]; then
    rm -r ${ADDON_DIR}/node_modules/.bin
  fi
  #if [ -e ${ADDON_DIR}/node_modules/@sindresorhus ]; then
  #  rm -r ${ADDON_DIR}/node_modules/@sindresorhus
  #fi
  #if [ -e ${ADDON_DIR}/node_modules/@szmarczak ]; then
  #  rm -r ${ADDON_DIR}/node_modules/@szmarczak
  #fi
  #if [ -e ${ADDON_DIR}/node_modules/cacheable-lookup ]; then
  #  rm -r ${ADDON_DIR}/node_modules/cacheable-lookup
  #fi
  #if [ -e ${ADDON_DIR}/node_modules/cacheable-request ]; then
  #  rm -r ${ADDON_DIR}/node_modules/cacheable-request
  #fi
  #if [ -e ${ADDON_DIR}/node_modules/clone-response ]; then
  #  rm -r ${ADDON_DIR}/node_modules/clone-response
  #fi
  #if [ -e ${ADDON_DIR}/node_modules/decompress-response ]; then
  #  rm -r ${ADDON_DIR}/node_modules/decompress-response
  #fi
  #if [ -e ${ADDON_DIR}/node_modules/defer-to-connect ]; then
  #  rm -r ${ADDON_DIR}/node_modules/defer-to-connect
  #fi
  #if [ -e ${ADDON_DIR}/node_modules/end-of-stream ]; then
  #  rm -r ${ADDON_DIR}/node_modules/end-of-stream
  #fi
  if [ -e ${ADDON_DIR}/node_modules/fs-extra ]; then
    rm -r ${ADDON_DIR}/node_modules/fs-extra
  fi
  #if [ -e ${ADDON_DIR}/node_modules/get-stream ]; then
  #  rm -r ${ADDON_DIR}/node_modules/get-stream
  #fi
  #if [ -e ${ADDON_DIR}/node_modules/got ]; then
  #  rm -r ${ADDON_DIR}/node_modules/got
  #fi
  if [ -e ${ADDON_DIR}/node_modules/got-hm ]; then
    rm -r ${ADDON_DIR}/node_modules/got-hm
  fi
  if [ -e ${ADDON_DIR}/node_modules/graceful-fs ]; then
    rm -r ${ADDON_DIR}/node_modules/graceful-fs
  fi
  #if [ -e ${ADDON_DIR}/node_modules/http2-wrapper ]; then
  #  rm -r ${ADDON_DIR}/node_modules/http2-wrapper
  #fi
  #if [ -e ${ADDON_DIR}/node_modules/http-cache-semantics ]; then
  #  rm -r ${ADDON_DIR}/node_modules/http-cache-semantics
  #fi
  #if [ -e ${ADDON_DIR}/node_modules/json-buffer ]; then
  #  rm -r ${ADDON_DIR}/node_modules/json-buffer
  #fi
  if [ -e ${ADDON_DIR}/node_modules/jsonfile ]; then
    rm -r ${ADDON_DIR}/node_modules/jsonfile
  fi
  #if [ -e ${ADDON_DIR}/node_modules/keyv ]; then
  #  rm -r ${ADDON_DIR}/node_modules/keyv
  #fi
  #if [ -e ${ADDON_DIR}/node_modules/lowercase-keys ]; then
  #  rm -r ${ADDON_DIR}/node_modules/lowercase-keys
  #fi
  #if [ -e ${ADDON_DIR}/node_modules/mimic-response ]; then
  #  rm -r ${ADDON_DIR}/node_modules/mimic-response
  #fi
  #if [ -e ${ADDON_DIR}/node_modules/normalize-url ]; then
  #  rm -r ${ADDON_DIR}/node_modules/normalize-url
  #fi
  #if [ -e ${ADDON_DIR}/node_modules/once ]; then
  #  rm -r ${ADDON_DIR}/node_modules/once
  #fi
  #if [ -e ${ADDON_DIR}/node_modules/p-cancelable ]; then
  #  rm -r ${ADDON_DIR}/node_modules/p-cancelable
  #fi
  #if [ -e ${ADDON_DIR}/node_modules/pump ]; then
  #  rm -r ${ADDON_DIR}/node_modules/pump
  #fi
  #if [ -e ${ADDON_DIR}/node_modules/quick-lru ]; then
  #  rm -r ${ADDON_DIR}/node_modules/quick-lru
  #fi
  #if [ -e ${ADDON_DIR}/node_modules/resolve-alpn ]; then
  #  rm -r ${ADDON_DIR}/node_modules/resolve-alpn
  #fi
  #if [ -e ${ADDON_DIR}/node_modules/responselike ]; then
  #  rm -r ${ADDON_DIR}/node_modules/responselike
  #fi
  if [ -e ${ADDON_DIR}/node_modules/universalify ]; then
    rm -r ${ADDON_DIR}/node_modules/universalify
  fi
  #if [ -e ${ADDON_DIR}/node_modules/wrappy ]; then
  #  rm -r ${ADDON_DIR}/node_modules/wrappy
  #fi
fi

# create necessary directories
mkdir -p ${ADDON_DIR}
chmod 755 ${ADDON_DIR}
mkdir -p ${RCD_DIR}
chmod 755 ${RCD_DIR}

# copy addon files
cp -af eufySecurity/* ${ADDON_DIR}/
cp -af eufySecurity-addon.cfg ${ADDON_DIR}/
cp -af VERSION ${ADDON_DIR}/

# make node executable
chmod 755 ${ADDON_DIR}/bin/node

# exclude some directories from backup
# (user will NEED to reinstall addon after restore)
touch ${ADDON_DIR}/bin/.nobackup
touch ${ADDON_DIR}/node_modules/.nobackup

# copy startup script
cp -af rc.d/* ${RCD_DIR}
chmod 755 ${RCD_DIR}/eufySecurity

# create www link
if [ ! -e ${WWW_DIR} ]; then
  ln -sf ${ADDON_DIR}/www ${WWW_DIR}
fi

sync

# exit with 0 to signal install succeeded
# if device is raspberrymatic then no reboot is requiered
# and so we have to start the service
# the original ccu will reboot by default
if [ "$1" = "HM-RASPBERRYMATIC" ]; then
  ${RCD_DIR}/eufySecurity start
fi
exit 0