#!/bin/bash
set -e

case "$1" in
  purge)
    ;;

  remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    rm -f /var/log/eufySecurity.log
    rm -f /var/log/eufySecurity.err
    rm -f /var/log/eufySecurityClient.log
    ;;
esac

