#!/bin/bash

set -e

case "$1" in
  remove|upgrade|deconfigure)
    #/usr/local/addons/eufySecurity/update_addon eufySecurity
    rm -f /usr/local/etc/config/addons/www/eufySecurity
    systemctl disable eufySecurity.service
    systemctl restart debmatic.service
    rm -rf /usr/local/addons/eufySecurity
    rm -f /var/log/eufySecurity.log
    rm -f /var/log/eufySecurity.err
    rm -f /var/log/eufySecurityClient.log
    ;;

  failed-upgrade)
    ;;
esac
